default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: tiennguyen
  database: toptal_jog_tracker_api_server_development


test:
  <<: *default
  username: tiennguyen
  database: toptal_jog_tracker_api_server_test


production:
  <<: *default
  username: tiennguyen
  database: toptal_jog_tracker_api_server
